In [27]:
!pip install pandas numpy faker openpyxl

Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\hp\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: faker in c:\users\hp\anaconda3\lib\site-packages (40.31.0)
Requirement already satisfied: openpyxl in c:\users\hp\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in c:\users\hp\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [28]:
import pandas as pd
import numpy as np
from faker import Faker
import random
from datetime import datetime, timedelta

In [29]:
fake = Faker("en_IN")

In [30]:
random.seed(42)
np.random.seed(42)

In [31]:
print(fake.name())
print(fake.city())
print(fake.email())

Andrew Lata
South Dumdum
obobal@example.com

In [32]:
cities = [
    "Delhi",
    "Mumbai",
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Pune",
    "Ahmedabad",
    "Jaipur",
    "Lucknow"
]

state_map = {
    "Delhi": "Delhi",
    "Mumbai": "Maharashtra",
    "Bengaluru": "Karnataka",
    "Hyderabad": "Telangana",
    "Chennai": "Tamil Nadu",
    "Kolkata": "West Bengal",
    "Pune": "Maharashtra",
    "Ahmedabad": "Gujarat",
    "Jaipur": "Rajasthan",
    "Lucknow": "Uttar Pradesh"
}

In [33]:
product_master = {
    "Samsung Galaxy S25": {
        "Category": "Smartphones",
        "Brand": "Samsung",
        "Unit_Price": 78000,
        "Cost_Price": 59000
    },

    "iPhone 16": {
        "Category": "Smartphones",
        "Brand": "Apple",
        "Unit_Price": 85000,
        "Cost_Price": 66000
    },

    "Google Pixel 9": {
        "Category": "Smartphones",
        "Brand": "Google",
        "Unit_Price": 70000,
        "Cost_Price": 55000
    },

    "OnePlus 13": {
        "Category": "Smartphones",
        "Brand": "OnePlus",
        "Unit_Price": 55000,
        "Cost_Price": 42000
    },

    "Dell Inspiron 15": {
        "Category": "Laptops",
        "Brand": "Dell",
        "Unit_Price": 65000,
        "Cost_Price": 50000
    },

    "HP Pavilion": {
        "Category": "Laptops",
        "Brand": "HP",
        "Unit_Price": 70000,
        "Cost_Price": 54000
    },

    "Lenovo ThinkPad E14": {
        "Category": "Laptops",
        "Brand": "Lenovo",
        "Unit_Price": 75000,
        "Cost_Price": 58000
    },

    "ASUS Vivobook": {
        "Category": "Laptops",
        "Brand": "ASUS",
        "Unit_Price": 62000,
        "Cost_Price": 47000
    },

    "MacBook Air M3": {
        "Category": "Laptops",
        "Brand": "Apple",
        "Unit_Price": 115000,
        "Cost_Price": 92000
    },

    "Samsung Galaxy Tab": {
        "Category": "Tablets",
        "Brand": "Samsung",
        "Unit_Price": 30000,
        "Cost_Price": 22000
    },

    "iPad Air": {
        "Category": "Tablets",
        "Brand": "Apple",
        "Unit_Price": 65000,
        "Cost_Price": 50000
    },

    "Lenovo Tab M11": {
        "Category": "Tablets",
        "Brand": "Lenovo",
        "Unit_Price": 25000,
        "Cost_Price": 18000
    },

    "Xiaomi Pad 7": {
        "Category": "Tablets",
        "Brand": "Xiaomi",
        "Unit_Price": 28000,
        "Cost_Price": 21000
    },

    "AirPods Pro": {
        "Category": "Audio",
        "Brand": "Apple",
        "Unit_Price": 25000,
        "Cost_Price": 18000
    },

    "Sony WH-1000XM5": {
        "Category": "Audio",
        "Brand": "Sony",
        "Unit_Price": 30000,
        "Cost_Price": 23000
    },

    "Boat Rockerz 550": {
        "Category": "Audio",
        "Brand": "boAt",
        "Unit_Price": 3000,
        "Cost_Price": 1800
    },

    "JBL Tune 770NC": {
        "Category": "Audio",
        "Brand": "JBL",
        "Unit_Price": 9000,
        "Cost_Price": 6000
    },

    "Apple Watch Series 10": {
        "Category": "Smart Watches",
        "Brand": "Apple",
        "Unit_Price": 45000,
        "Cost_Price": 34000
    },

    "Samsung Galaxy Watch 7": {
        "Category": "Smart Watches",
        "Brand": "Samsung",
        "Unit_Price": 35000,
        "Cost_Price": 26000
    },

    "Noise ColorFit Pro": {
        "Category": "Smart Watches",
        "Brand": "Noise",
        "Unit_Price": 6000,
        "Cost_Price": 3500
    },

    "Power Bank": {
        "Category": "Accessories",
        "Brand": "Ambrane",
        "Unit_Price": 2000,
        "Cost_Price": 1200
    },

    "Wireless Mouse": {
        "Category": "Accessories",
        "Brand": "Logitech",
        "Unit_Price": 1200,
        "Cost_Price": 700
    },

    "Mechanical Keyboard": {
        "Category": "Accessories",
        "Brand": "Redragon",
        "Unit_Price": 3500,
        "Cost_Price": 2200
    },

    "Laptop Backpack": {
        "Category": "Accessories",
        "Brand": "Wildcraft",
        "Unit_Price": 2500,
        "Cost_Price": 1500
    },

    "USB-C Hub": {
        "Category": "Accessories",
        "Brand": "Anker",
        "Unit_Price": 3000,
        "Cost_Price": 1800
    }
}

In [34]:
print("Total Products:", len(product_master))

for product, details in product_master.items():
    print(product, "->", details["Brand"])

Total Products: 25
Samsung Galaxy S25 -> Samsung
iPhone 16 -> Apple
Google Pixel 9 -> Google
OnePlus 13 -> OnePlus
Dell Inspiron 15 -> Dell
HP Pavilion -> HP
Lenovo ThinkPad E14 -> Lenovo
ASUS Vivobook -> ASUS
MacBook Air M3 -> Apple
Samsung Galaxy Tab -> Samsung
iPad Air -> Apple
Lenovo Tab M11 -> Lenovo
Xiaomi Pad 7 -> Xiaomi
AirPods Pro -> Apple
Sony WH-1000XM5 -> Sony
Boat Rockerz 550 -> boAt
JBL Tune 770NC -> JBL
Apple Watch Series 10 -> Apple
Samsung Galaxy Watch 7 -> Samsung
Noise ColorFit Pro -> Noise
Power Bank -> Ambrane
Wireless Mouse -> Logitech
Mechanical Keyboard -> Redragon
Laptop Backpack -> Wildcraft
USB-C Hub -> Anker

In [35]:
payment_modes = [
    "UPI",
    "Credit Card",
    "Debit Card",
    "Cash",
    "Net Banking"
]

customer_segments = [
    "Regular",
    "Premium",
    "Corporate"
]

sales_channels = [
    "Online",
    "Offline"
]

salespersons = [
    "Amit Sharma",
    "Priya Verma",
    "Rahul Mehta",
    "Neha Singh",
    "Rohit Gupta",
    "Anjali Kapoor",
    "Vikas Yadav",
    "Sneha Iyer"
]

In [36]:
sales_data = []

In [37]:
for i in range(1, 10001):

    order_id = f"ORD{i:06d}"

    customer_name = fake.name()

    gender = random.choice(["Male", "Female"])

    age = random.randint(18, 65)

    city = random.choice(cities)
    state = state_map[city]

    product = random.choice(list(product_master.keys()))

    details = product_master[product]

    category = details["Category"]
    brand = details["Brand"]
    unit_price = details["Unit_Price"]
    cost_price = details["Cost_Price"]

    quantity = random.randint(1, 5)

    discount_percent = random.choice([0, 5, 10, 15, 20])

    sales_amount = quantity * unit_price

    discount_amount = round(
        sales_amount * discount_percent / 100,
        2
    )

    taxable_amount = sales_amount - discount_amount

    gst = round(taxable_amount * 0.18, 2)

    final_amount = round(
        taxable_amount + gst,
        2
    )

    total_cost = quantity * cost_price

    profit = round(
        taxable_amount - total_cost,
        2
    )

    profit_margin = round(
        (profit / taxable_amount) ,
        4
    ) if taxable_amount > 0 else 0

    payment_mode = random.choice(payment_modes)

    customer_segment = random.choice(customer_segments)

    sales_channel = random.choice(sales_channels)

    salesperson = random.choice(salespersons)

    order_date = fake.date_between(
        start_date="-2y",
        end_date="today"
    )

    sales_data.append([
        order_id,
        customer_name,
        gender,
        age,
        city,
        state,
        category,
        product,
        brand,
        quantity,
        unit_price,
        cost_price,
        total_cost,
        discount_percent,
        discount_amount,
        sales_amount,
        gst,
        final_amount,
        profit,
        profit_margin,
        payment_mode,
        customer_segment,
        sales_channel,
        salesperson,
        order_date
    ])

In [38]:
len(sales_data)

10000

In [39]:
columns = [
    "Order_ID",
    "Customer_Name",
    "Gender",
    "Age",
    "City",
    "State",
    "Category",
    "Product",
    "Brand",
    "Quantity",
    "Unit_Price",
    "Cost_Price",
    "Total_Cost",
    "Discount_%",
    "Discount_Amount",
    "Sales_Amount",
    "GST",
    "Final_Amount",
    "Profit",
    "Profit_Margin_%",
    "Payment_Mode",
    "Customer_Segment",
    "Sales_Channel",
    "Salesperson",
    "Order_Date"
]

df = pd.DataFrame(sales_data, columns=columns)

In [40]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

df["Order_Month"] = df["Order_Date"].dt.month_name()

df["Quarter"] = "Q" + df["Order_Date"].dt.quarter.astype(str)

df["Day_Name"] = df["Order_Date"].dt.day_name()

region_map = {
    "Delhi": "North",
    "Mumbai": "West",
    "Bengaluru": "South",
    "Hyderabad": "South",
    "Chennai": "South",
    "Kolkata": "East",
    "Pune": "West",
    "Ahmedabad": "West",
    "Jaipur": "North",
    "Lucknow": "North"
}

df["Region"] = df["City"].map(region_map)


df["Delivery_Days"] = np.random.randint(1, 8, len(df))


df["Customer_Rating"] = np.random.choice(
    [3, 4, 5],
    size=len(df),
    p=[0.15, 0.35, 0.50]
)


df["Return_Status"] = np.random.choice(
    ["Returned", "Not Returned"],
    size=len(df),
    p=[0.08, 0.92]
)


df["Coupon_Used"] = np.random.choice(
    ["Yes", "No"],
    size=len(df),
    p=[0.35, 0.65]
)


df["Loyalty_Member"] = np.random.choice(
    ["Yes", "No"],
    size=len(df),
    p=[0.40, 0.60]
)


df["Customer_Type"] = np.random.choice(
    ["New", "Returning"],
    size=len(df),
    p=[0.35, 0.65]
)


df["Payment_Status"] = np.random.choice(
    ["Paid", "Pending"],
    size=len(df),
    p=[0.95, 0.05]
)


df["Delivery_Status"] = np.random.choice(
    ["Delivered", "In Transit", "Cancelled"],
    size=len(df),
    p=[0.88, 0.10, 0.02]
)


df["Stock_Status"] = np.random.choice(
    ["In Stock", "Low Stock", "Out of Stock"],
    size=len(df),
    p=[0.70, 0.20, 0.10]
)


def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Summer"
    elif month in [6, 7, 8, 9]:
        return "Monsoon"
    else:
        return "Festive"

df["Season"] = df["Order_Date"].dt.month.apply(get_season)

In [41]:
print("Rows, Columns:", df.shape)
print("\n")

print("Missing Values")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

print("\nData Types")
print(df.dtypes)

Rows, Columns: (10000, 39)


Missing Values
Order_ID            0
Customer_Name       0
Gender              0
Age                 0
City                0
State               0
Category            0
Product             0
Brand               0
Quantity            0
Unit_Price          0
Cost_Price          0
Total_Cost          0
Discount_%          0
Discount_Amount     0
Sales_Amount        0
GST                 0
Final_Amount        0
Profit              0
Profit_Margin_%     0
Payment_Mode        0
Customer_Segment    0
Sales_Channel       0
Salesperson         0
Order_Date          0
Order_Month         0
Quarter             0
Day_Name            0
Region              0
Delivery_Days       0
Customer_Rating     0
Return_Status       0
Coupon_Used         0
Loyalty_Member      0
Customer_Type       0
Payment_Status      0
Delivery_Status     0
Stock_Status        0
Season              0
dtype: int64

Duplicate Rows: 0

Data Types
Order_ID                    object
Customer_Name               object
Gender                      object
Age                          int64
City                        object
State                       object
Category                    object
Product                     object
Brand                       object
Quantity                     int64
Unit_Price                   int64
Cost_Price                   int64
Total_Cost                   int64
Discount_%                   int64
Discount_Amount            float64
Sales_Amount                 int64
GST                        float64
Final_Amount               float64
Profit                     float64
Profit_Margin_%            float64
Payment_Mode                object
Customer_Segment            object
Sales_Channel               object
Salesperson                 object
Order_Date          datetime64[ns]
Order_Month                 object
Quarter                     object
Day_Name                    object
Region                      object
Delivery_Days                int32
Customer_Rating              int64
Return_Status               object
Coupon_Used                 object
Loyalty_Member              object
Customer_Type               object
Payment_Status              object
Delivery_Status             object
Stock_Status                object
Season                      object
dtype: object

In [42]:
df.head()

,Order_ID,Customer_Name,Gender,Age,City,State,Category,Product,Brand,Quantity,...,Delivery_Days,Customer_Rating,Return_Status,Coupon_Used,Loyalty_Member,Customer_Type,Payment_Status,Delivery_Status,Stock_Status,Season
0,ORD000001,Anita Bhardwaj,Male,19,Chennai,Tamil Nadu,Laptops,ASUS Vivobook,ASUS,2,...,7,5,Not Returned,Yes,No,Returning,Paid,In Transit,Low Stock,Festive
1,ORD000002,Rushil Upadhyay,Male,19,Mumbai,Maharashtra,Laptops,Lenovo ThinkPad E14,Lenovo,2,...,4,5,Not Returned,No,No,Returning,Pending,Delivered,In Stock,Monsoon
2,ORD000003,Lekha Khanna,Male,46,Lucknow,Uttar Pradesh,Laptops,MacBook Air M3,Apple,1,...,5,3,Returned,No,No,New,Paid,Delivered,Low Stock,Festive
3,ORD000004,Theodore Dugal,Male,39,Mumbai,Maharashtra,Smartphones,Google Pixel 9,Google,4,...,7,5,Not Returned,No,No,Returning,Paid,Delivered,In Stock,Winter
4,ORD000005,Niharika Dayal,Female,52,Mumbai,Maharashtra,Tablets,Xiaomi Pad 7,Xiaomi,1,...,3,4,Not Returned,No,Yes,Returning,Paid,Cancelled,Low Stock,Winter

In [45]:
df.to_excel("RetailPulse_Analytics_2025_Final.xlsx", index=False)

print("✅ Dataset exported successfully!")

✅ Dataset exported successfully!

In [46]:
data_dictionary = pd.DataFrame({
    "Column_Name": df.columns,
    "Data_Type": df.dtypes.astype(str).values
})

data_dictionary.to_excel("RetailPulse_Data_Dictionary.xlsx", index=False)

print("✅ Data Dictionary created!")

✅ Data Dictionary created!

In [47]:
print("="*50)
print("RETAILPULSE ANALYTICS DATASET SUMMARY")
print("="*50)

print(f"Total Rows: {df.shape[0]}")
print(f"Total Columns: {df.shape[1]}")

print("\nColumn Names:")
for col in df.columns:
    print(col)

==================================================
RETAILPULSE ANALYTICS DATASET SUMMARY
==================================================
Total Rows: 10000
Total Columns: 39

Column Names:
Order_ID
Customer_Name
Gender
Age
City
State
Category
Product
Brand
Quantity
Unit_Price
Cost_Price
Total_Cost
Discount_%
Discount_Amount
Sales_Amount
GST
Final_Amount
Profit
Profit_Margin_%
Payment_Mode
Customer_Segment
Sales_Channel
Salesperson
Order_Date
Order_Month
Quarter
Day_Name
Region
Delivery_Days
Customer_Rating
Return_Status
Coupon_Used
Loyalty_Member
Customer_Type
Payment_Status
Delivery_Status
Stock_Status
Season

In [48]:
df.describe(include="all")

,Order_ID,Customer_Name,Gender,Age,City,State,Category,Product,Brand,Quantity,...,Delivery_Days,Customer_Rating,Return_Status,Coupon_Used,Loyalty_Member,Customer_Type,Payment_Status,Delivery_Status,Stock_Status,Season
count,10000,10000,10000,10000.000000,10000,10000,10000,10000,10000,10000.000000,...,10000.000000,10000.000000,10000,10000,10000,10000,10000,10000,10000,10000
unique,10000,9828,2,NaN,10,9,6,25,18,NaN,...,NaN,NaN,2,2,2,2,2,3,3,4
top,ORD000001,Orinder Sunder,Female,NaN,Bengaluru,Maharashtra,Accessories,Sony WH-1000XM5,Apple,NaN,...,NaN,NaN,Not Returned,No,No,Returning,Paid,Delivered,In Stock,Monsoon
freq,1,3,5036,NaN,1031,2003,2032,433,1990,NaN,...,NaN,NaN,9222,6496,6005,6598,9441,8784,7036,3344
mean,NaN,NaN,NaN,41.253000,NaN,NaN,NaN,NaN,NaN,3.002700,...,4.008700,4.352300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,18.000000,NaN,NaN,NaN,NaN,NaN,1.000000,...,1.000000,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,29.000000,NaN,NaN,NaN,NaN,NaN,2.000000,...,2.000000,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,41.000000,NaN,NaN,NaN,NaN,NaN,3.000000,...,4.000000,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,53.000000,NaN,NaN,NaN,NaN,NaN,4.000000,...,6.000000,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,65.000000,NaN,NaN,NaN,NaN,NaN,5.000000,...,7.000000,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,13.796631,NaN,NaN,NaN,NaN,NaN,1.414741,...,1.998555,0.726524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
df.to_csv("RetailPulse_Analytics_2025_Final.csv", index=False)

print("CSV Saved Successfully!")

CSV Saved Successfully!

In [50]:
df["Order_Status"] = np.random.choice(
    ["Delivered", "Processing", "Cancelled", "Returned"],
    size=len(df),
    p=[0.82, 0.10, 0.03, 0.05]
)

df["Order_Status"].value_counts()

Order_Status
Delivered     8244
Processing     982
Returned       503
Cancelled      271
Name: count, dtype: int64

In [51]:
df["Shipping_Mode"] = np.random.choice(
    ["Standard", "Express", "Same Day"],
    size=len(df),
    p=[0.65, 0.25, 0.10]
)

df["Shipping_Mode"].value_counts()

Shipping_Mode
Standard    6491
Express     2496
Same Day    1013
Name: count, dtype: int64

In [52]:
print("="*60)
print("RetailPulse Analytics 2025 - Final Dataset Summary")
print("="*60)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

print("\nMissing Values")
print(df.isnull().sum().sum())

print("\nDuplicate Rows")
print(df.duplicated().sum())

============================================================
RetailPulse Analytics 2025 - Final Dataset Summary
============================================================
Rows    : 10000
Columns : 41

Missing Values
0

Duplicate Rows
0

In [53]:
df.to_excel("RetailPulse_Analytics_2025_Final.xlsx", index=False)


df.to_csv("RetailPulse_Analytics_2025_Final.csv", index=False)

print("✅ Excel File Saved")
print("✅ CSV File Saved")

✅ Excel File Saved
✅ CSV File Saved

In [54]:
data_dictionary = pd.DataFrame({
    "Column_Name": df.columns,
    "Data_Type": df.dtypes.astype(str)
})

data_dictionary.to_excel(
    "RetailPulse_Data_Dictionary.xlsx",
    index=False
)

print("✅ Data Dictionary Saved")

✅ Data Dictionary Saved